package(
    default_visibility = ["//visibility:public"],
)

config_setting(
    name = "aarch64_mode",
    values = {"cpu": "aarch64"},
)

config_setting(
    name = "x86_mode",
    values = {"cpu": "k8"},
)

config_setting(
    name = "override_eigen_strong_inline",
    values = {"define": "override_eigen_strong_inline=true"},
)
